In [5]:
import numpy as np

In [12]:
def gauss_jordan(A, b):
    
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = A.shape[0]
    M = np.hstack([A, b])
    
    
    for l in range(n):
        pivot = M[l, l]
        if abs(pivot) < 1e-12:
            continue
        
        fator = pivot
        M[l, :] = M[l, :] / fator
        print(f"\n Trabalhando na coluna {l}")
        print(f"L{l} <- L{l} / {fator}")
        print(M)
        
        for ll in range(n):
            if ll == l:
                continue
            f = M[ll, l]
            M[ll, :] = M[ll, :] - f * M[l, :]
        
            print(f"\n Trabalhando na coluna {l}")
            print(f"L{ll} <- L{ll} - {f} L{l}")
            print(M)
    
    w = M[:, -1]
    return w, M



In [13]:
A = np.array([[1, 1, 1], [2, 3, 7], [1, -1, 2]])

b = np.array([[6], [20], [4]])

print(A)
print(b)

[[ 1  1  1]
 [ 2  3  7]
 [ 1 -1  2]]
[[ 6]
 [20]
 [ 4]]


In [ ]:
w, _ = gauss_jordan(A, b)
print(w)



 Trabalhando na coluna 0
L0 <- L0 / 1.0
[[ 1.  1.  1.  6.]
 [ 2.  3.  7. 20.]
 [ 1. -1.  2.  4.]]

 Trabalhando na coluna 0
L1 <- L1 - 2.0 L0
[[ 1.  1.  1.  6.]
 [ 0.  1.  5.  8.]
 [ 1. -1.  2.  4.]]

 Trabalhando na coluna 0
L2 <- L2 - 1.0 L0
[[ 1.  1.  1.  6.]
 [ 0.  1.  5.  8.]
 [ 0. -2.  1. -2.]]

 Trabalhando na coluna 1
L1 <- L1 / 1.0
[[ 1.  1.  1.  6.]
 [ 0.  1.  5.  8.]
 [ 0. -2.  1. -2.]]

 Trabalhando na coluna 1
L0 <- L0 - 1.0 L1
[[ 1.  0. -4. -2.]
 [ 0.  1.  5.  8.]
 [ 0. -2.  1. -2.]]

 Trabalhando na coluna 1
L2 <- L2 - -2.0 L1
[[ 1.  0. -4. -2.]
 [ 0.  1.  5.  8.]
 [ 0.  0. 11. 14.]]

 Trabalhando na coluna 2
L2 <- L2 / 11.0
[[ 1.          0.         -4.         -2.        ]
 [ 0.          1.          5.          8.        ]
 [ 0.          0.          1.          1.27272727]]

 Trabalhando na coluna 2
L0 <- L0 - -4.0 L2
[[1.         0.         0.         3.09090909]
 [0.         1.         5.         8.        ]
 [0.         0.         1.         1.27272727]]

 Trabalha