In [8]:
import numpy as np

In [9]:
def gauss_jordan(A, b):
    
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float).reshape(-1, 1)
    n = A.shape[0]
    M = np.hstack([A, b])
    
    
    for l in range(n):
        pivot = M[l, l]
        if abs(pivot) < 1e-12:
            continue
        
        fator = pivot
        M[l, :] = M[l, :] / fator
        print(f"\n Trabalhando na coluna {l}")
        print(f"L{l} <- L{l} / {fator}")
        print(M)
        
        for ll in range(n):
            if ll == l:
                continue
            f = M[ll, l]
            M[ll, :] = M[ll, :] - f * M[l, :]
        
            print(f"\n Trabalhando na coluna {l}")
            print(f"L{ll} <- L{ll} - {f} L{l}")
            print(M)
    
    w = M[:, -1]
    return w, M



In [10]:
A = np.array([[1, 1, 1], [2, 3, 7], [1, -1, 2]])

b = np.array([[6], [20], [4]])

print(A)
print(b)

[[ 1  1  1]
 [ 2  3  7]
 [ 1 -1  2]]
[[ 6]
 [20]
 [ 4]]


In [11]:
w, _ = gauss_jordan(A, b)
print(w)


 Trabalhando na coluna 0
L0 <- L0 / 1.0
[[ 1.  1.  1.  6.]
 [ 2.  3.  7. 20.]
 [ 1. -1.  2.  4.]]

 Trabalhando na coluna 0
L1 <- L1 - 2.0 L0
[[ 1.  1.  1.  6.]
 [ 0.  1.  5.  8.]
 [ 1. -1.  2.  4.]]

 Trabalhando na coluna 0
L2 <- L2 - 1.0 L0
[[ 1.  1.  1.  6.]
 [ 0.  1.  5.  8.]
 [ 0. -2.  1. -2.]]

 Trabalhando na coluna 1
L1 <- L1 / 1.0
[[ 1.  1.  1.  6.]
 [ 0.  1.  5.  8.]
 [ 0. -2.  1. -2.]]

 Trabalhando na coluna 1
L0 <- L0 - 1.0 L1
[[ 1.  0. -4. -2.]
 [ 0.  1.  5.  8.]
 [ 0. -2.  1. -2.]]

 Trabalhando na coluna 1
L2 <- L2 - -2.0 L1
[[ 1.  0. -4. -2.]
 [ 0.  1.  5.  8.]
 [ 0.  0. 11. 14.]]

 Trabalhando na coluna 2
L2 <- L2 / 11.0
[[ 1.          0.         -4.         -2.        ]
 [ 0.          1.          5.          8.        ]
 [ 0.          0.          1.          1.27272727]]

 Trabalhando na coluna 2
L0 <- L0 - -4.0 L2
[[1.         0.         0.         3.09090909]
 [0.         1.         5.         8.        ]
 [0.         0.         1.         1.27272727]]

 Trabalha

In [12]:
def matrizd(x, d:int):
    x = np.array(x, dtype=float)
    cols = [np.ones_like(x)] + [x**k for k in range(1, d+1)]
    return np.column_stack(cols)

def sums_S_T(x, y, d:int):
    x = np.array(x, dtype=float)
    y = np.array(y, dtype=float)
    
    S = [np.sum(x**k) for k in range(2*d + 1)]

    T = [np.sum((x**k) * y) for k in range(d + 1)]
    return S, T

def gerapelasoma(S, T, d:int):
    XtX = np.empty((d+1, d+1))
    for j in range(d+1):
        for k in range(d+1):
            XtX[j, k] = S[j + k]

    Xty = np.array(T, dtype=float)
    
    return XtX, Xty


def RMSE():
    pass

In [13]:
x = [0, 1, 2, 3, 4]
y = [1.2, 2.9, 5.1, 6.8, 9.2]


In [14]:
S, T = sums_S_T(x, y, 1)
print(S)
print(T)

[np.float64(5.0), np.float64(10.0), np.float64(30.0)]
[np.float64(25.2), np.float64(70.3)]


In [24]:
x = [0, 1, 2, 3, 4]
y = [1, 3, 4, 5, 13]

mx = matrizd(x, 2)
print(mx)

[[ 1.  0.  0.]
 [ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]]
